# Title: Drag Race 0.2.0
# Author: Dallas Gianniny
# Date: July 3 2020

#Changelog: 
#   Set console size
#   Color single player assets
#   Change in tree timing. A true NHRA Pro tree will have 0.400 seconds between amber lights and the greeen light.
        # amberToGreenSecs sets new time at 0.200 seconds to better represent slipping forces of a real car

# TODO: More intelligent AI opponent (currently only has dynamic staging times)
# TODO: Multiplayer Support
# TODO: Redlight reaction time (negative reaction time)
# TODO: Better edge case behavior of art assets

import time
import random
import msvcrt
from pynput import keyboard
import os
from colorama import Fore, Back, Style, init

os.system('mode con: cols=154 lines=44')
init(autoreset=True)

startFlag = True
restartFlag = False
foulFlag = False
a = 0.0
b = 0.0
amberToGreenSecs = 0.2
input_char = ''

def startTitleText():
    print(Fore.MAGENTA+Style.BRIGHT+"                                            ________                         __________                      ")
    print(Fore.MAGENTA+Style.BRIGHT+"                                            \______ \____________     ____   \______   \_____    ____  ____  ")
    print(Fore.MAGENTA+Style.BRIGHT+"                                             |    |  \_  __ \__  \   / ___\   |       _/\__  \ _/ ___\/ __ \ ")
    print(Fore.MAGENTA+Style.BRIGHT+"                                             |    `   \  | \// __ \_/ /_/  >  |    |   \ / __ \\  \__\  ___/ ")
    print(Fore.MAGENTA+Style.BRIGHT+"                                            /_______  /__|  (____  /\___  /   |____|_  /(____  /\___  >___  >")
    print(Fore.MAGENTA+Style.BRIGHT+"                                                    \/           \//_____/           \/      \/     \/    \/ ")

def startTitleVersionText():
    print(Fore.MAGENTA+Style.BRIGHT+"                                                                    ____   ___    ____ ")
    print(Fore.MAGENTA+Style.BRIGHT+"                                                                   / __ \ |__ \  / __ \ ")
    print(Fore.MAGENTA+Style.BRIGHT+"                                                                  / / / / __/ / / / / /")
    print(Fore.MAGENTA+Style.BRIGHT+"                                                                 / /_/ / / __/_/ /_/ / ")
    print(Fore.MAGENTA+Style.BRIGHT+"                                                                 \____(_)____(_)____/  ")
    print(Fore.MAGENTA+Style.BRIGHT+"                                                                                       ")

def xToStartText():
    print(Fore.CYAN+Style.BRIGHT+"                                  ___ ___ ___ ___ ___  __  __             ")
    print(Fore.CYAN+Style.BRIGHT+"                                 | _ \ _ \ __/ __/ __| \ \/ /             ")
    print(Fore.CYAN+Style.BRIGHT+"                                 |  _/   / _|\__ \__ \  >  <              ")
    print(Fore.CYAN+Style.BRIGHT+"                                 |_|_|_|_\___|___/___/_/_/\_\ ___ _____ _ ")
    print(Fore.CYAN+Style.BRIGHT+"                                  |_   _/ _ \  / __|_   _/_\ | _ \_   _| |")
    print(Fore.CYAN+Style.BRIGHT+"                                    | || (_) | \__ \ | |/ _ \|   / | | |_|")
    print(Fore.CYAN+Style.BRIGHT+"                                    |_| \___/  |___/ |_/_/ \_\_|_\ |_| (_)")
    print(Fore.CYAN+Style.BRIGHT+"                                                                          ")

def xToStartText2():
    print(Fore.CYAN+Style.BRIGHT+"                                                ____     ____     ______   _____   _____          _  __     ")
    print(Fore.CYAN+Style.BRIGHT+"                                               / __ \   / __ \   / ____/  / ___/  / ___/         | |/ /     ")
    print(Fore.CYAN+Style.BRIGHT+"                                              / /_/ /  / /_/ /  / __/     \__ \   \__ \          |   /      ")
    print(Fore.CYAN+Style.BRIGHT+"                                             / ____/  / _, _/  / /___    ___/ /  ___/ /         /   |       ")
    print(Fore.CYAN+Style.BRIGHT+"                                            /_/      /_/ |_|  /_____/   /____/  /____/         /_/|_|       ")
    print(Fore.CYAN+Style.BRIGHT+"                                              ______   ____           _____  ______    ___     ____   ______")
    print(Fore.CYAN+Style.BRIGHT+"                                             /_  __/  / __ \         / ___/ /_  __/   /   |   / __ \ /_  __/")
    print(Fore.CYAN+Style.BRIGHT+"                                              / /    / / / /         \__ \   / /     / /| |  / /_/ /  / /   ")
    print(Fore.CYAN+Style.BRIGHT+"                                             / /    / /_/ /         ___/ /  / /     / ___ | / _, _/  / /    ")
    print(Fore.CYAN+Style.BRIGHT+"                                            /_/     \____/         /____/  /_/     /_/  |_|/_/ |_|  /_/     ")
    print(Fore.CYAN+Style.BRIGHT+"                                                                                                            ")

def howToPlayText():
    print(Fore.WHITE+Style.BRIGHT+"                          _  _  _____      __  _____ ___    ___ _      ___   __")
    print(Fore.WHITE+Style.BRIGHT+"                         | || |/ _ \ \    / / |_   _/ _ \  | _ \ |    /_\ \ / /")
    print(Fore.WHITE+Style.BRIGHT+"                         | __ | (_) \ \/\/ /    | || (_) | |  _/ |__ / _ \ V / ")
    print(Fore.WHITE+Style.BRIGHT+"                         |_||_|\___/ \_/\_/     |_| \___/  |_| |____/_/ \_\_|  ")
    print(Fore.WHITE+Style.BRIGHT+"                                                                               ")

def howToPlayText2():
    print(Fore.WHITE+Style.BRIGHT+"    __  __   ____  _       __         ______   ____            ____     __     ___ __  __")
    print(Fore.WHITE+Style.BRIGHT+"   / / / /  / __ \| |     / /        /_  __/  / __ \          / __ \   / /    /   |\ \/ /")
    print(Fore.WHITE+Style.BRIGHT+"  / /_/ /  / / / /| | /| / /          / /    / / / /         / /_/ /  / /    / /| | \  / ")
    print(Fore.WHITE+Style.BRIGHT+" / __  /  / /_/ / | |/ |/ /          / /    / /_/ /         / ____/  / /___ / ___ | / /  ")
    print(Fore.WHITE+Style.BRIGHT+"/_/ /_/   \____/  |__/|__/          /_/     \____/         /_/      /_____//_/  |_|/_/   ")
    print(Fore.WHITE+Style.BRIGHT+"                                                                                         ")

def rules_0():
    print(Fore.RED+"                          _     _     ___   _                 _              __ _        _           ")
    print(Fore.RED+"     _ __ _ _ ___ ______ / |  _| |_  |_  ) | |_ ___   ___ _ _| |_ ___ _ _   / _(_)_ _ __| |_         ")
    print(Fore.RED+"    | '_ \ '_/ -_|_-<_-< | | |_   _|  / /  |  _/ _ \ / -_) ' \  _/ -_) '_| |  _| | '_(_-<  _|        ")
    print(Fore.RED+"    | .__/_| \___/__/__/ |_|   |_|   /___|  \__\___/_\___|_||_\__\___|_|   |_| |_|_| /__/\__|        ")
    print(Fore.RED+"    |_| _ _ _  __| |  ___ ___ __ ___ _ _  __| |  __| |_ __ _ __ _(_)_ _  __ _   __ _ _ _ ___ __ _ ___")
    print(Fore.RED+"    / _` | ' \/ _` | (_-</ -_) _/ _ \ ' \/ _` | (_-<  _/ _` / _` | | ' \/ _` | / _` | '_/ -_) _` (_-<")
    print(Fore.RED+"    \__,_|_||_\__,_| /__/\___\__\___/_||_\__,_| /__/\__\__,_\__, |_|_||_\__, | \__,_|_| \___\__,_/__/")
    print(Fore.RED+"                                                            |___/       |___/                        ")
    print(Fore.RED+"    / _` | ' \/ _` | (_-</ -_) _/ _ \ ' \/ _` | (_-<  _/ _` / _` | | ' \/ _` | / _` | '_/ -_) _` (_-<")
    print(Fore.RED+"    \__,_|_||_\__,_| /__/\___\__\___/_||_\__,_| /__/\__\__,_\__, |_|_||_\__, | \__,_|_| \___\__,_/__/")
    print(Fore.RED+"                                                            |___/       |___/                        ")

def rules_02():
    print(Fore.RED+"                                      ___            ___      __                         __                 ____ _              __           ")
    print(Fore.RED+"    ____   _____ ___   _____ _____   <  /    __     |__ \    / /_ ____     ___   ____   / /_ ___   _____   / __/(_)_____ _____ / /_          ")
    print(Fore.RED+"   / __ \ / ___// _ \ / ___// ___/   / /  __/ /_    __/ /   / __// __ \   / _ \ / __ \ / __// _ \ / ___/  / /_ / // ___// ___// __/          ")
    print(Fore.RED+"  / /_/ // /   /  __/(__  )(__  )   / /  /_  __/   / __/   / /_ / /_/ /  /  __// / / // /_ /  __// /     / __// // /   (__  )/ /_            ")
    print(Fore.RED+" / .___//_/    \___//____//____/   /_/    /_/     /____/   \__/ \____/   \___//_/ /_/ \__/ \___//_/     /_/  /_//_/   /____/ \__/            ")
    print(Fore.RED+"/_/                  __                                       __         __                 _                                                ")
    print(Fore.RED+"  ____ _ ____   ____/ /  _____ ___   _____ ____   ____   ____/ /  _____ / /_ ____ _ ____ _ (_)____   ____ _   ____ _ _____ ___   ____ _ _____")
    print(Fore.RED+" / __ `// __ \ / __  /  / ___// _ \ / ___// __ \ / __ \ / __  /  / ___// __// __ `// __ `// // __ \ / __ `/  / __ `// ___// _ \ / __ `// ___/")
    print(Fore.RED+"/ /_/ // / / // /_/ /  (__  )/  __// /__ / /_/ // / / // /_/ /  (__  )/ /_ / /_/ // /_/ // // / / // /_/ /  / /_/ // /   /  __// /_/ /(__  ) ")
    print(Fore.RED+"\__,_//_/ /_/ \__,_/  /____/ \___/ \___/ \____//_/ /_/ \__,_/  /____/ \__/ \__,_/ \__, //_//_/ /_/ \__, /   \__,_//_/    \___/ \__,_//____/  ")
    print(Fore.RED+"                                                                                 /____/           /____/                                     ")

def rules_1():
    print(Fore.GREEN+"                       _                    _                                       _   _        _    _ ")
    print(Fore.GREEN+"  ___ _ _  __ ___   __| |_ __ _ __ _ ___ __| |    _ __ _ _ ___ ______  __ _ _ _  __| | | |_  ___| |__| |")
    print(Fore.GREEN+" / _ \ ' \/ _/ -_) (_-<  _/ _` / _` / -_) _` |_  | '_ \ '_/ -_|_-<_-< / _` | ' \/ _` | | ' \/ _ \ / _` |")
    print(Fore.GREEN+" \___/_||_\__\___| /__/\__\__,_\__, \___\__,_( ) | .__/_| \___/__/__/ \__,_|_||_\__,_| |_||_\___/_\__,_|")
    print(Fore.GREEN+"                  _            |___/         |/  |_|                                       _            ")
    print(Fore.GREEN+"  __ _ _ _ _  _  | |_____ _  _  | |_ ___   _ _ _____ __  _  _ ___ _  _ _ _   ___ _ _  __ _(_)_ _  ___   ")
    print(Fore.GREEN+" / _` | ' \ || | | / / -_) || | |  _/ _ \ | '_/ -_) V / | || / _ \ || | '_| / -_) ' \/ _` | | ' \/ -_)  ")
    print(Fore.GREEN+" \__,_|_||_\_, | |_\_\___|\_, |  \__\___/ |_| \___|\_/   \_, \___/\_,_|_|   \___|_||_\__, |_|_||_\___|  ")
    print(Fore.GREEN+"           |__/           |__/                           |__/                        |___/              ")

def rules_12():
    print(Fore.GREEN+"                                     __                           __                                                         __   __            __     __")
    print(Fore.GREEN+"  ____   ____   _____ ___     _____ / /_ ____ _ ____ _ ___   ____/ /     ____   _____ ___   _____ _____   ____ _ ____   ____/ /  / /_   ____   / /____/ /")
    print(Fore.GREEN+" / __ \ / __ \ / ___// _ \   / ___// __// __ `// __ `// _ \ / __  /     / __ \ / ___// _ \ / ___// ___/  / __ `// __ \ / __  /  / __ \ / __ \ / // __  / ")
    print(Fore.GREEN+"/ /_/ // / / // /__ /  __/  (__  )/ /_ / /_/ // /_/ //  __// /_/ /_    / /_/ // /   /  __/(__  )(__  )  / /_/ // / / // /_/ /  / / / // /_/ // // /_/ /  ")
    print(Fore.GREEN+"\____//_/ /_/ \___/ \___/  /____/ \__/ \__,_/ \__, / \___/ \__,_/( )  / .___//_/    \___//____//____/   \__,_//_/ /_/ \__,_/  /_/ /_/ \____//_/ \__,_/   ")
    print(Fore.GREEN+"                                             /____/              |/  /_/                                                                                 ")
    print(Fore.GREEN+"                          __                   __                                                                                 _                      ")
    print(Fore.GREEN+"  ____ _ ____   __  __   / /__ ___   __  __   / /_ ____     _____ ___  _   __   __  __ ____   __  __ _____   ___   ____   ____ _ (_)____   ___           ")
    print(Fore.GREEN+" / __ `// __ \ / / / /  / //_// _ \ / / / /  / __// __ \   / ___// _ \| | / /  / / / // __ \ / / / // ___/  / _ \ / __ \ / __ `// // __ \ / _ \          ")
    print(Fore.GREEN+"/ /_/ // / / // /_/ /  / ,<  /  __// /_/ /  / /_ / /_/ /  / /   /  __/| |/ /  / /_/ // /_/ // /_/ // /     /  __// / / // /_/ // // / / //  __/          ")
    print(Fore.GREEN+"\__,_//_/ /_/ \__, /  /_/|_| \___/ \__, /   \__/ \____/  /_/    \___/ |___/   \__, / \____/ \__,_//_/      \___//_/ /_/ \__, //_//_/ /_/ \___/           ")
    print(Fore.GREEN+"             /____/               /____/                                     /____/                                    /____/                            ")

def rules_2():
    print(Fore.YELLOW+"                            _                    _   _          _              _       ")
    print(Fore.YELLOW+"                    _ _ ___| |___ __ _ ___ ___  | |_| |_  ___  | |_____ _  _  | |_ ___ ")
    print(Fore.YELLOW+"                   | '_/ -_) / -_) _` (_-</ -_) |  _| ' \/ -_) | / / -_) || | |  _/ _ \ ")
    print(Fore.YELLOW+"                   |_| \___|_\___\__,_/__/\___|  \__|_||_\___| |_\_\___|\_, |  \__\___/")
    print(Fore.YELLOW+"                      ___  ___     ___  _  _  __   _____ _    _    _____|__/  ___      ")
    print(Fore.YELLOW+"                     / __|/ _ \   / _ \| \| | \ \ / / __| |  | |  / _ \ \    / / |     ")
    print(Fore.YELLOW+"                    | (_ | (_) | | (_) | .` |  \ V /| _|| |__| |_| (_) \ \/\/ /|_|     ")
    print(Fore.YELLOW+"                     \___|\___/   \___/|_|\_|   |_| |___|____|____\___/ \_/\_/ (_)     ")
    print(Fore.YELLOW+"                                                                                       ")

def rules_22():
    print(Fore.YELLOW+"                __                            __   __             __                   __            ______ ____   __")
    print(Fore.YELLOW+"   _____ ___   / /___   ____ _ _____ ___     / /_ / /_   ___     / /__ ___   __  __   / /_ ____     / ____// __ \ / /")
    print(Fore.YELLOW+"  / ___// _ \ / // _ \ / __ `// ___// _ \   / __// __ \ / _ \   / //_// _ \ / / / /  / __// __ \   / / __ / / / // /  ")
    print(Fore.YELLOW+" / /   /  __// //  __// /_/ /(__  )/  __/  / /_ / / / //  __/  / ,<  /  __// /_/ /  / /_ / /_/ /  / /_/ // /_/ //_/  ")
    print(Fore.YELLOW+"/_/    \___//_/ \___/ \__,_//____/ \___/   \__//_/ /_/ \___/  /_/|_| \___/ \__, /   \__/ \____/   \____/ \____/(_)   ")
    print(Fore.YELLOW+"                                                                          /____/                                     ")

def freshTree():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |"+Fore.YELLOW+Style.DIM+"___  ___ ___ ___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.DIM+"/ _ \/ _ \___|___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.DIM+"\___/\___/       \___/\___/"+Style.RESET_ALL+" |")
    print("               |_|                         |_|")
    print("               | |"+Fore.YELLOW+Style.DIM+"___  ___ ___ ___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.DIM+"/ _ \/ _ \___|___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.DIM+"\___/\___/       \___/\___/"+Style.RESET_ALL+" |")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.GREEN+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.GREEN+Style.DIM+"__         ")
    print("                       "+Fore.GREEN+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"|/  \        ")
    print("                      "+Fore.GREEN+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"| () |       ")
    print("                       "+Fore.GREEN+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.GREEN+Style.DIM+"|\__/        ")
    print("                        "+Fore.RED+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.RED+Style.DIM+"__         ")
    print("                       "+Fore.RED+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|/  \        ")
    print("                      "+Fore.RED+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"| () |       ")
    print("                       "+Fore.RED+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|\__/        ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def freshTreeBright():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |"+Fore.YELLOW+Style.BRIGHT+"___  ___ ___ ___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"/ _ \/ _ \___|___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"\___/\___/       \___/\___/"+Style.RESET_ALL+" |")
    print("               |_|                         |_|")
    print("               | |"+Fore.YELLOW+Style.BRIGHT+"___  ___ ___ ___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"/ _ \/ _ \___|___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"\___/\___/       \___/\___/"+Style.RESET_ALL+" |")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.GREEN+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.GREEN+Style.DIM+"__         ")
    print("                       "+Fore.GREEN+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"|/  \        ")
    print("                      "+Fore.GREEN+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"| () |       ")
    print("                       "+Fore.GREEN+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.GREEN+Style.DIM+"|\__/        ")
    print("                        "+Fore.RED+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.RED+Style.DIM+"__         ")
    print("                       "+Fore.RED+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|/  \        ")
    print("                      "+Fore.RED+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"| () |       ")
    print("                       "+Fore.RED+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|\__/        ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def leftStage1():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |"+Fore.YELLOW+Style.BRIGHT+"_ __\ \/ /__ "+Style.RESET_ALL+Fore.YELLOW+Style.DIM+"___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"\ \ / >  <___|"+Style.RESET_ALL+Fore.YELLOW+Style.DIM+"___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"/_\_\/_/\_\   "+Style.RESET_ALL+Fore.YELLOW+Style.DIM+"   \___/\___/ "+Style.RESET_ALL+"|")
    print("               |_|                         |_|")
    print("               | |"+Fore.YELLOW+Style.DIM+"___  ___ ___ ___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.DIM+"/ _ \/ _ \___|___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.DIM+"\___/\___/       \___/\___/ "+Style.RESET_ALL+"|")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.GREEN+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.GREEN+Style.DIM+"__         ")
    print("                       "+Fore.GREEN+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"|/  \        ")
    print("                      "+Fore.GREEN+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"| () |       ")
    print("                       "+Fore.GREEN+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.GREEN+Style.DIM+"|\__/        ")
    print("                        "+Fore.RED+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.RED+Style.DIM+"__         ")
    print("                       "+Fore.RED+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|/  \        ")
    print("                      "+Fore.RED+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"| () |       ")
    print("                       "+Fore.RED+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|\__/        ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def rightStage1():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |___  ___ ___ __\ \/ /__ _| |")
    print("               | / _ \/ _ \___|___>  < \ \ / |")
    print("               | \___/\___/      /_/\_\/_\_\ |")
    print("               |_|                         |_|")
    print("               | |___  ___ ___ ___ ___  ___| |")
    print("               | / _ \/ _ \___|___/ _ \/ _ \ |")
    print("               | \___/\___/       \___/\___/ |")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                       /  \| | | |/  \        ")
    print("                      | () | | | | () |       ")
    print("                       \__/| | | |\__/        ")
    print("                        __ |_|_|_| __         ")
    print("                       /  \| | | |/  \        ")
    print("                      | () | | | | () |       ")
    print("                       \__/| | | |\__/        ")
    print("                        __ |_|_|_| __         ")
    print("                       /  \| | | |/  \        ")
    print("                      | () | | | | () |       ")
    print("                       \__/| | | |\__/        ")
    print("                        __ |_|_|_| __         ")
    print("                       /  \| | | |/  \        ")
    print("                      | () | | | | () |       ")
    print("                       \__/| | | |\__/        ")
    print("                        __ |_|_|_| __         ")
    print("                       /  \| | | |/  \        ")
    print("                      | () | | | | () |       ")
    print("                       \__/| | | |\__/        ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def bothStage1():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |"+Fore.YELLOW+Style.BRIGHT+"_ __\ \/ /__ __\ \/ /__ _"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"\ \ / >  <___|___>  < \ \ / "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"/_\_\/_/\_\     /_/\_\/_\_\ "+Style.RESET_ALL+"|")
    print("               |_|                         |_|")
    print("               | |"+Fore.YELLOW+Style.DIM+"___  ___ ___ ___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.DIM+"/ _ \/ _ \___|___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.DIM+"\___/\___/       \___/\___/ "+Style.RESET_ALL+"|")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.GREEN+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.GREEN+Style.DIM+"__         ")
    print("                       "+Fore.GREEN+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"|/  \        ")
    print("                      "+Fore.GREEN+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"| () |       ")
    print("                       "+Fore.GREEN+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.GREEN+Style.DIM+"|\__/        ")
    print("                        "+Fore.RED+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.RED+Style.DIM+"__         ")
    print("                       "+Fore.RED+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|/  \        ")
    print("                      "+Fore.RED+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"| () |       ")
    print("                       "+Fore.RED+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|\__/        ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def leftStage2():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |"+Fore.YELLOW+Style.BRIGHT+"_ __\ \/ /__ __\ \/ /__ _"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"\ \ / >  <___|___>  < \ \ / "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"/_\_\/_/\_\     /_/\_\/_\_\ "+Style.RESET_ALL+"|")
    print("               |_|    "+Fore.YELLOW+Style.BRIGHT+"__  __               "+Style.RESET_ALL+"|_|")
    print("               | |"+Fore.YELLOW+Style.BRIGHT+"_ __\ \/ /__ "+Style.RESET_ALL+Fore.YELLOW+Style.DIM+"___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"\ \ / >  <___|"+Style.RESET_ALL+Fore.YELLOW+Style.DIM+"___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"/_\_\/_/\_\   "+Style.RESET_ALL+Fore.YELLOW+Style.DIM+"   \___/\___/ "+Style.RESET_ALL+"|")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.GREEN+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.GREEN+Style.DIM+"__         ")
    print("                       "+Fore.GREEN+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"|/  \        ")
    print("                      "+Fore.GREEN+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"| () |       ")
    print("                       "+Fore.GREEN+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.GREEN+Style.DIM+"|\__/        ")
    print("                        "+Fore.RED+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.RED+Style.DIM+"__         ")
    print("                       "+Fore.RED+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|/  \        ")
    print("                      "+Fore.RED+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"| () |       ")
    print("                       "+Fore.RED+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|\__/        ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def rightStage2():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |_ __\ \/ /__ __\ \/ /__ _| |")
    print("               | \ \ / >  <___|___>  < \ \ / |")
    print("               | /_\_\/_/\_\     /_/\_\/_\_\ |")
    print("               |_|               __  __    |_|")
    print("               | |___  ___ ___ __\ \/ /__ _| |")
    print("               | / _ \/ _ \___|___>  < \ \ / |")
    print("               | \___/\___/      /_/\_\/_\_\ |")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                       /  \| | | |/  \        ")
    print("                      | () | | | | () |       ")
    print("                       \__/| | | |\__/        ")
    print("                        __ |_|_|_| __         ")
    print("                       /  \| | | |/  \        ")
    print("                      | () | | | | () |       ")
    print("                       \__/| | | |\__/        ")
    print("                        __ |_|_|_| __         ")
    print("                       /  \| | | |/  \        ")
    print("                      | () | | | | () |       ")
    print("                       \__/| | | |\__/        ")
    print("                        __ |_|_|_| __         ")
    print("                       /  \| | | |/  \        ")
    print("                      | () | | | | () |       ")
    print("                       \__/| | | |\__/        ")
    print("                        __ |_|_|_| __         ")
    print("                       /  \| | | |/  \        ")
    print("                      | () | | | | () |       ")
    print("                       \__/| | | |\__/        ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def bothStage2():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |"+Fore.YELLOW+Style.BRIGHT+"_ __\ \/ /__ __\ \/ /__ _"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"\ \ / >  <___|___>  < \ \ / "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"/_\_\/_/\_\     /_/\_\/_\_\ "+Style.RESET_ALL+"|")
    print("               |_|    "+Fore.YELLOW+Style.BRIGHT+"__  __     __  __    "+Style.RESET_ALL+"|_|")
    print("               | |"+Fore.YELLOW+Style.BRIGHT+"_ __\ \/ /__ __\ \/ /__ _"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"\ \ / >  <___|___>  < \ \ / "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"/_\_\/_/\_\     /_/\_\/_\_\ "+Style.RESET_ALL+"|")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.GREEN+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.GREEN+Style.DIM+"__         ")
    print("                       "+Fore.GREEN+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"|/  \        ")
    print("                      "+Fore.GREEN+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"| () |       ")
    print("                       "+Fore.GREEN+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.GREEN+Style.DIM+"|\__/        ")
    print("                        "+Fore.RED+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.RED+Style.DIM+"__         ")
    print("                       "+Fore.RED+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|/  \        ")
    print("                      "+Fore.RED+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"| () |       ")
    print("                       "+Fore.RED+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|\__/        ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def amberLights():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |"+Fore.YELLOW+Style.BRIGHT+"_ __\ \/ /__ __\ \/ /__ _"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"\ \ / >  <___|___>  < \ \ / "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"/_\_\/_/\_\     /_/\_\/_\_\ "+Style.RESET_ALL+"|")
    print("               |_|    "+Fore.YELLOW+Style.BRIGHT+"__  __     __  __    "+Style.RESET_ALL+"|_|")
    print("               | |"+Fore.YELLOW+Style.BRIGHT+"_ __\ \/ /__ __\ \/ /__ _"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"\ \ / >  <___|___>  < \ \ / "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.BRIGHT+"/_\_\/_/\_\     /_/\_\/_\_\ "+Style.RESET_ALL+"|")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"\ \/ / "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.BRIGHT+"\ \/ /       ")
    print("                       "+Fore.YELLOW+Style.BRIGHT+">  <| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.BRIGHT+"|>  <        ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"/_/\_\ "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.BRIGHT+"/_/\_\       ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"__  _"+Style.RESET_ALL+"|_|_|_|"+Fore.YELLOW+Style.BRIGHT+"_  __       ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"\ \/ / "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.BRIGHT+"\ \/ /       ")
    print("                       "+Fore.YELLOW+Style.BRIGHT+">  <| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.BRIGHT+"|>  <        ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"/_/\_\ "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.BRIGHT+"/_/\_\       ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"__  _"+Style.RESET_ALL+"|_|_|_|"+Fore.YELLOW+Style.BRIGHT+"_  __       ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"\ \/ / "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.BRIGHT+"\ \/ /       ")
    print("                       "+Fore.YELLOW+Style.BRIGHT+">  <| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.BRIGHT+"|>  <        ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"/_/\_\ "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.BRIGHT+"/_/\_\       ")
    print("                        "+Fore.GREEN+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.GREEN+Style.DIM+"__         ")
    print("                       "+Fore.GREEN+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"|/  \        ")
    print("                      "+Fore.GREEN+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.DIM+"| () |       ")
    print("                       "+Fore.GREEN+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.GREEN+Style.DIM+"|\__/        ")
    print("                        "+Fore.RED+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.RED+Style.DIM+"__         ")
    print("                       "+Fore.RED+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|/  \        ")
    print("                      "+Fore.RED+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"| () |       ")
    print("                       "+Fore.RED+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|\__/        ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def bothGreenLights():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |"+Fore.YELLOW+Style.DIM+"___  ___ ___ ___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.DIM+"/ _ \/ _ \___|___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.DIM+"\___/\___/       \___/\___/"+Style.RESET_ALL+" |")
    print("               |_|                         |_|")
    print("               | |"+Fore.YELLOW+Style.DIM+"___  ___ ___ ___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.DIM+"/ _ \/ _ \___|___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.DIM+"\___/\___/       \___/\___/"+Style.RESET_ALL+" |")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.YELLOW+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                       "+Fore.YELLOW+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                      "+Fore.YELLOW+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                       "+Fore.YELLOW+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                "+Fore.GREEN+Style.BRIGHT+"__  ____  _"+Style.RESET_ALL+"|_|_|_|"+Fore.GREEN+Style.BRIGHT+"_  ____  __ ")
    print("                "+Fore.GREEN+Style.BRIGHT+"\ \/ /\ \/ /"+Style.RESET_ALL+" | | "+Fore.GREEN+Style.BRIGHT+"\ \/ /\ \/ / ")
    print("                 "+Fore.GREEN+Style.BRIGHT+">  <  >  <|"+Style.RESET_ALL+" | | "+Fore.GREEN+Style.BRIGHT+"|>  <  >  <  ")
    print("                "+Fore.GREEN+Style.BRIGHT+"/_/\_\/_/\_\ "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.BRIGHT+"/_/\_\/_/\_\ ")
    print("                        "+Fore.RED+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_| "+Fore.RED+Style.DIM+"__         ")
    print("                       "+Fore.RED+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|/  \        ")
    print("                      "+Fore.RED+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"| () |       ")
    print("                       "+Fore.RED+Style.DIM+"\__/|"+Style.RESET_ALL+" | | "+Fore.RED+Style.DIM+"|\__/        ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def bothRedLight():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |"+Fore.YELLOW+Style.DIM+"___  ___ ___ ___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.DIM+"/ _ \/ _ \___|___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.DIM+"\___/\___/       \___/\___/"+Style.RESET_ALL+" |")
    print("               |_|                         |_|")
    print("               | |"+Fore.YELLOW+Style.DIM+"___  ___ ___ ___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.DIM+"/ _ \/ _ \___|___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.DIM+"\___/\___/       \___/\___/"+Style.RESET_ALL+" |")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                      \ \/ / | | \ \/ /       ")
    print("                       >  <| | | |>  <        ")
    print("                      /_/\_\ | | /_/\_\       ")
    print("                      __  _|_|_|_|_  __       ")
    print("                      \ \/ / | | \ \/ /       ")
    print("                       >  <| | | |>  <        ")
    print("                      /_/\_\ | | /_/\_\       ")
    print("                      __  _|_|_|_|_  __       ")
    print("                      \ \/ / | | \ \/ /       ")
    print("                       >  <| | | |>  <        ")
    print("                      /_/\_\ | | /_/\_\       ")
    print("                        __ |_|_|_| __         ")
    print("                       /  \| | | |/  \        ")
    print("                      | () | | | | () |       ")
    print("                       \__/| | | |\__/        ")
    print("                __  ____  _|_|_|_|_  ____  __ ")
    print("                \ \/ /\ \/ / | | \ \/ /\ \/ / ")
    print("                 >  <  >  <| | | |>  <  >  <  ")
    print("                /_/\_\/_/\_\ | | /_/\_\/_/\_\ ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def leftRedLight():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |"+Fore.YELLOW+Style.DIM+"___  ___ ___ ___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.DIM+"/ _ \/ _ \___|___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.DIM+"\___/\___/       \___/\___/"+Style.RESET_ALL+" |")
    print("               |_|                         |_|")
    print("               | |"+Fore.YELLOW+Style.DIM+"___  ___ ___ ___ ___  ___"+Style.RESET_ALL+"| |")
    print("               | "+Fore.YELLOW+Style.DIM+"/ _ \/ _ \___|___/ _ \/ _ \ "+Style.RESET_ALL+"|")
    print("               | "+Fore.YELLOW+Style.DIM+"\___/\___/       \___/\___/"+Style.RESET_ALL+" |")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"\ \/ / "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                       "+Fore.YELLOW+Style.BRIGHT+">  <| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"/_/\_\ "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"__  _"+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"\ \/ / "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                       "+Fore.YELLOW+Style.BRIGHT+">  <| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"/_/\_\ "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"__  _"+Style.RESET_ALL+"|_|_|_| "+Fore.YELLOW+Style.DIM+"__         ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"\ \/ / "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|/  \        ")
    print("                       "+Fore.YELLOW+Style.BRIGHT+">  <| "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"| () |       ")
    print("                      "+Fore.YELLOW+Style.BRIGHT+"/_/\_\ "+Style.RESET_ALL+"| | "+Fore.YELLOW+Style.DIM+"|\__/        ")
    print("                        "+Fore.RED+Style.DIM+"__ "+Style.RESET_ALL+"|_|_|_|"+Fore.GREEN+Style.BRIGHT+"_  __       ")
    print("                       "+Fore.RED+Style.DIM+"/  \| "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.BRIGHT+"\ \/ /       ")
    print("                      "+Fore.RED+Style.DIM+"| () | "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.BRIGHT+"|>  <        ")
    print("                       "+Fore.RED+Style.DIM+"\__/| "+Style.RESET_ALL+"| | "+Fore.GREEN+Style.BRIGHT+"/_/\_\       ")
    print("                "+Fore.RED+Style.BRIGHT+"__  ____  _"+Style.RESET_ALL+"|_|_|_| "+Fore.RED+Style.DIM+"__         ")
    print("                "+Fore.RED+Style.BRIGHT+"\ \/ /\ \/ /"+Style.RESET_ALL+" | | "+Fore.RED+Style.DIM+"|/  \        ")
    print("                 "+Fore.RED+Style.BRIGHT+">  <  >  <|"+Style.RESET_ALL+" | | "+Fore.RED+Style.DIM+"| () |       ")
    print("                "+Fore.RED+Style.BRIGHT+"/_/\_\/_/\_\ "+Style.RESET_ALL+"| | "+Fore.RED+Style.DIM+"|\__/        ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def rightRedLight():
    print("                                              ")
    print("                                              ")
    print("                                              ")
    print("                 ___ ___ ___ ___ ___ ___ ___  ")
    print("                |___|___|___|___|___|___|___| ")
    print("               | |___  ___ ___ ___ ___  ___| |")
    print("               | / _ \/ _ \___|___/ _ \/ _ \ |")
    print("               | \___/\___/       \___/\___/ |")
    print("               |_|                         |_|")
    print("               | |___  ___ ___ ___ ___  ___| |")
    print("               | / _ \/ _ \___|___/ _ \/ _ \ |")
    print("               | \___/\___/       \___/\___/ |")
    print("               |_|__ ___ ___ ___ ___ ___ __|_|")
    print("                |___|___|___|___|___|___|___| ")
    print("                       /  \| | | \ \/ /       ")
    print("                      | () | | | |>  <        ")
    print("                       \__/| | | /_/\_\       ")
    print("                        __ |_|_|_|_  __       ")
    print("                       /  \| | | \ \/ /       ")
    print("                      | () | | | |>  <        ")
    print("                       \__/| | | /_/\_\       ")
    print("                        __ |_|_|_|_  __       ")
    print("                       /  \| | | \ \/ /       ")
    print("                      | () | | | |>  <        ")
    print("                       \__/| | | /_/\_\       ")
    print("                      __  _|_|_|_| __         ")
    print("                      \ \/ / | | |/  \        ")
    print("                       >  <| | | | () |       ")
    print("                      /_/\_\ | | |\__/        ")
    print("                        __ |_|_|_|_  ____  __ ")
    print("                       /  \| | | \ \/ /\ \/ / ")
    print("                      | () | | | |>  <  >  <  ")
    print("                       \__/| | | /_/\_\/_/\_\ ")
    print("                           |_|_|_|            ")
    print("                           | | | |            ")
    print("                           | | | |            ")
    print("                           | | | |            ")

def redLightText():
    print(Fore.RED+Style.BRIGHT+"  ___ ___ ___  _    ___ ___ _  _ _____ _ ")
    print(Fore.RED+Style.BRIGHT+" | _ \ __|   \| |  |_ _/ __| || |_   _| |")
    print(Fore.RED+Style.BRIGHT+" |   / _|| |) | |__ | | (_ | __ | | | |_|")
    print(Fore.RED+Style.BRIGHT+" |_|_\___|___/|____|___\___|_||_| |_| (_)")
    print(Fore.RED+Style.BRIGHT+"                                         ")

def rematch():
    print(Fore.WHITE+"  ___ ___ __  __   _ _____ ___ _  _ ___    __ __   __    __  _  _  __  ")
    print(Fore.WHITE+" | _ \ __|  \/  | /_\_   _/ __| || |__ \  / / \ \ / /   / / | \| | \ \  ")
    print(Fore.WHITE+" |   / _|| |\/| |/ _ \| || (__| __ | /_/ | |   \ V /   / /  | .` |  | |")
    print(Fore.WHITE+" |_|_\___|_|  |_/_/ \_\_| \___|_||_|(_)  | |    |_|   /_/   |_|\_|  | |")
    print(Fore.WHITE+"                                          \_\                      /_/ ")

def newLines(num):
    returnString = ''
    for x in range(num):
        returnString += "\n"
        x += 1
    print(returnString)

def setStartFlag(inputBool):
    global startFlag
    startFlag = inputBool

def setRestartFlag(inputBool):
    global restartFlag
    restartFlag = inputBool
        
def setFoulFlag(inputBool):
    global foulFlag
    foulFlag = inputBool

def resetTimer():
    global a, b
    a = 0.0
    b = 0.0

def clearConsole():
    os.system('cls')

def on_key_release(key):
    global a, b
    b = time.perf_counter()
    # if (b < a):
    #     setFoulFlag(True)
    #     newLines(1)
    #     leftRedLight()
    #     print("     " + str(a - b)[:6] + " Seconds RT")
    if (a == 0):
        setFoulFlag(True)
        newLines(1)
        leftRedLight()
        redLightText()
    else: 
        print("     " + str(b - a)[:5] + " Seconds RT")
    return False

while (startFlag):
    listener = keyboard.Listener(on_release = on_key_release)
    resetTimer()
    clearConsole()
    newLines(20)
    startTitleText()
    newLines(1)
    startTitleVersionText()
    newLines(10)
    if not(restartFlag):
        xToStartText2()
    else:
        newLines(5)
        time.sleep(1.5)

    while 1:
        if not(restartFlag):
            input_char = msvcrt.getch()
            if input_char.upper() == b'X':
                # if not(restartFlag):
                clearConsole()
                #newLines(10)
                howToPlayText2()
                newLines(1)
                rules_02()
                newLines(2)
                rules_12()
                newLines(2)
                rules_22()
                time.sleep(6.66)
                clearConsole()
                #newLines(10)
                freshTree()
                break
        elif (restartFlag):
            clearConsole()
            #newLines(10)
            freshTree()
            break
        else:
            continue
    
    while 1:
        input_char = msvcrt.getch()
        if input_char.upper() == b'1':
            clearConsole()
            #newLines(5)
            leftStage1()
            time.sleep(random.uniform(0.5,5.0))
            clearConsole()
            #newLines(5)
            bothStage1()
            break
        else:
            continue

    while not(foulFlag):
        input_char = msvcrt.getch()
        if input_char.upper() == b'2':
            clearConsole()
            #newLines(5)
            leftStage2()
            time.sleep(random.uniform(0.2,7.0))
            clearConsole()
            #newLines(5)
            bothStage2()
            listener.start()
            time.sleep(1)
            while not(foulFlag):
                clearConsole()
                #newLines(5)
                amberLights()
                time.sleep(amberToGreenSecs)
                break
            while not(foulFlag):
                clearConsole()
                #newLines(5)
                bothGreenLights()
                a = time.perf_counter()
                time.sleep(0.002)
                break
            break
        else:
            continue

    time.sleep(1.5)   
    rematch()
    
    while 1:
        input_char = msvcrt.getch()
        if input_char.upper() == b'Y':
            setStartFlag(True)
            setRestartFlag(True)
            setFoulFlag(False)
            listener.stop()
            break
        elif input_char.upper() == b'N':
            setStartFlag(False)
            break
        else:
            continue